name: "Nix Builder"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
    - uses: cachix/cachix-action@v12
      with:
        name: dynamicdevices
        extraPullNames: devenv
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix profile install github:cachix/devenv/latest
      name: Install devenv.sh
    - run: devenv ci
    - run: nix build
